### ISSUE TITLE
commands in any order need to be executed

### ISSUE THREAD

**Issue by Razia-Shaheen-Sara** [RenataKaras/minishell#3]
>out2 cat Makefile should make a output  file and put Makefile contents in it. It should not error and execute.

so 2 things need to be done:

1. execute the comand
2. remove the error  message

**Comment by Razia-Shaheen-Sara** [comment]
same goes for the input redirection
 <Makefile grep fclean 
bash executes this command but we do not

**Comment by RenataKaras** [comment]
I've just checked how the AST looks like for these two cases, and this is what I pass on to you:
1. for `>out2 cat Makefile`:

> Node Type: CMD
Args: out2 cat Makefile
IO Redirections:
  IO Type: Output Redirection (> or >>)
  IO Value: out2

2. for `<Makefile grep fclean`:

> Node Type: CMD
Args: Makefile grep fclean
IO Redirections:
  IO Type: Input Redirection (<)
  IO Value: Makefile
  
 do you see anything here that you think is an issue? From a first glance to me it looks correct.
