### ISSUE TITLE
catting heredoc to the stdout doesn't work

### ISSUE THREAD

**Issue by RenataKaras** [RenataKaras/minishell#7]
`cat << EOF` only opens a heredoc but after the EOF it doesn't print it out on the STDOUT

**Comment by RenataKaras** [comment]
I think this is somehow connected to this as well and it has to do with the fact that when we call heredoc it doesn't process anything else other than heredoc - another example is 
`<< EOF | wc > testout `
It doesn't create testout or does a pipe

**Comment by Razia-Shaheen-Sara** [comment]
A premature return was causing it.

**Comment by RenataKaras** [comment]
`<< EOF | wc > testout ` doesn't work

**Comment by RenataKaras** [comment]
> `<< EOF | wc > testout ` doesn't work

this now works, but the prompt for the heredoc says `pipe heredoc>` and it should be changed

**Comment by RenataKaras** [comment]
> `<< EOF | wc > testout ` doesn't work

it now creates testout file but when I cat it I get 0 0 0, no matter what I type in the heredoc.
Let's see what Jan says about it - are we supposed to have this working or not.
